### PR TITLE
BigModel Provider Addition

### PR DESCRIPTION
**Pull request by Oelshehawi**
# Description
Implements BigModel provider adapter with proper error handling.

## Key Changes
- Add BigModel adapter extending OpenAISDKChatAdapter 
- Implement retry logic with exponential backoff for rate limits
- Handle Chinese-specific error messages ("未正常接收到prompt参数", "messages 参数非法")
- Add proper type hints and overloads for async execution

## Model Support
Added All GLM models with CNY pricing (following Moonshot's pattern lines 16-32):

## Testing
- All tests passing
- Mypy type checking passing
- Proper error handling verified

### CODE REVIEW

**Comment by DexSniffer** [comment]
Hello, is there anyway i can have this reviewed soon, or maybe i can contanct support?
-Thank you

**Comment by 0xcmd** [comment]
Thank you so much! Will be waiting for your reply!

**Review by LukeSamkharadze — APPROVED** [review]

**Comment by LukeSamkharadze** [comment]
Thanks for the contribution. Merging!

**Comment by LukeSamkharadze** [comment]
Fixed pricing [here](https://github.com/withmartian/llm-adapters/pull/134)

**Comment by DexSniffer** [comment]
Thank you so much. ive tried contacting your customer support through the web interface, is there a better place as this was not the only contribution i had planned. Thank for reviewing!

**Comment by LukeSamkharadze** [comment]
@DexSniffer You can create issues on github or contact me directly

**Comment by 0xcmd** [comment]
Hey Luke, I'm the one who submitted big models. I'm also like the second
person to fork the repo and I will say you did not make that easy to do at
all. Actually if I had to guess you dont want people doing it lol.  Not one
dev I knew could do it and I had to use AI all the way through. Took me 20
hours non stop but I finally got my endpoint. It was So worth it. Insane
what I've accomplished with it.

Ive restricted my self from Making videos about martian. Its too good to
give away. All my content goes viral and I was wondering if you had an
affiliate link?  Also I'd like a job with Martian. I'd rebrand everything
to martian and pump my same content. You did an amazing job literally noone
knows what this is. I run a discord and a tiktok and we are going to be
building these out and configuring them as part of our company package as a
premium model for rag applications. I'm currently building one purely for
embedding models. Anyway exciting stuff.

Regards-
Justyn

**Comment by LukeSamkharadze** [comment]
Hey @0xcmd, could you email me at `lukesamkharadze@icloud.com`?

Let's have a call to discuss some

**Comment by 0xcmd** [comment]
Hey Luke, Do you mind telling me what endpoint im supposed to use? for
microsoft azure.

Thanks,
Justyn

**Comment by LukeSamkharadze** [comment]
We don't have proper azure support as of now. But as far as I know when you register for Azure, they give you custom endpoint

**Comment by 0xcmd** [comment]
Ya ive figured it out, but on your front end you accept azure base url and
api key. And I've tested and it works fine, now I'm off to DATABricks to
move my models from azure over to a group in databricks similar to github.
Then Turn my azure endpoint Into agents and or flows. Should be
interesting. Ive made a custom prompt for router using openweb frameworks,
3 system prompts clashing together lol it literally thinks and reasons with
the router, will stop, think and continue. I had to get azure cause I was
hitting limits hard.

Most fun I've had in a long time.

Thanks again for making it.
Bts I'm still looking for that affiliate link or marketing job you have
posted.

Regards
Justyn

**Comment by LukeSamkharadze** [comment]
Could you contact me on email for ways to collaborate?

`lukesamkharadze@icloud.com` or
`luka@withmartian.com`

**Pull request merged**
